--Q1:
SELECT e.*, d.* FROM EMPLOYEES e CROSS JOIN DEPARTMENTS d;

--Q2:
SELECT d.*, e.* FROM DEPARTMENTS d LEFT JOIN EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID;

--Q3:
SELECT d.EMPLOYEE_NAME AS EMPLOYEE_NAMES, m.EMPLOYEE_NAME AS MANAGER_NAMES FROM EMPLOYEES d INNER JOIN EMPLOYEES m ON d.MANAGER_ID = m.EMPLOYEE_ID;

--Q4:
SELECT * FROM EMPLOYEES e WHERE e.EMPLOYEE_ID NOT IN (SELECT p.EMPLOYEE_ID FROM EMPLOYEE_PROJECT_ASSIGNMENT p);

--Q5:
SELECT s.STUDENT_NAME, c.COURSE_NAME FROM STUDENTS s INNER JOIN ENROLLMENTS e ON s.STUDENT_ID = e.STUDENT_ID INNER JOIN COURSES c ON e.COURSE_ID = c.COURSE_ID;

--Q6:
SELECT c.*, o.* FROM CUSTOMERS c LEFT JOIN ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID;

--Q7:
SELECT d.*, e.* FROM DEPARTMENTS d LEFT JOIN EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID;

--Q8:
SELECT t.*, s.* FROM TEACHERS t CROSS JOIN SUBJECTS s;

--Q9:
SELECT DEPARTMENT_ID, COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

--Q10:
SELECT s.STUDENT_NAME, s.SUBJECT_NAME, t.TEACHER_NAME FROM STUDENTS s INNER JOIN ENROLLMENTS e ON s.STUDENT_ID = e.STUDENT_ID INNER JOIN SUBJECTS s ON e.COURSE_ID = s.SUBJECT_ID INNER JOIN TEACHERS t ON s.TEACHER_ID = t.TEACHER_ID;
