--Q11:
SELECT * FROM STUDENTS s JOIN TEACHERS t ON s.CITY = t.CITY;

--Q12:
SELECT e.EMPLOYEE_NAME AS EMPLOYEE_NAMES, m.EMPLOYEE_NAME AS MANAGER_NAMES FROM EMPLOYEES e LEFT JOIN EMPLOYEES m ON e.MANAGER_ID = m.MANAGER_ID;

--Q13:
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IS NULL;

--Q14:
SELECT d.DEPARTMENT_ID, d.DEPARTMENT_NAME, AVG(e.SALARY) AS AVERAGE_SALARY FROM EMPLOYEES e JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID GROUP BY d.DEPARTMENT_ID, d.DEPARTMENT_NAME HAVING AVG(e.SALARY) > 50000;

--Q15:
SELECT * FROM EMPLOYEES e1 WHERE e1.SALARY > (SELECT AVG(e2.SALARY) FROM EMPLOYEES e2 WHERE e1.DEPARTMENT_ID = e2.DEPARTMENT_ID GROUP BY e2.DEPARTMENT_ID);

--Q16:
SELECT d.DEPARTMENT_ID, d.DEPARTMENT_NAME FROM DEPARTMENTS d JOIN EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID GROUP BY d.DEPARTMENT_ID, d.DEPARTMENT_NAME HAVING MIN(e.SALARY) >= 30000;

--Q17:
SELECT s.*, c.* FROM STUDENTS s JOIN ENROLLMENTS e ON s.STUDENT_ID = e.STUDENT_ID JOIN COURSES c ON e.COURSE_ID = c.COURSE_ID WHERE s.CITY = 'Lahore';

--Q18:
SELECT e.EMPLOYEE_ID, e.EMPLOYEE_NAME, d.DEPARTMENT_ID, d.DEPARTMENT_NAME, m.EMPLOYEE_ID AS MANAGER_ID, m.EMPLOYEE_NAME AS MANAGER_NAME, e.HIRE_DATE FROM EMPLOYEES e JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID WHERE e.HIRE_DATE BETWEEN '01-JAN-2020' AND '01-JAN-2023';

--Q19:
SELECT s.* FROM STUDENTS s JOIN EnROLLMENTS e ON s.STUDENT_ID = e.STUDENT_ID JOIN COURSES c ON e.COURSE_ID = c.COURSE_ID JOIN TEACHERS t ON c.TEACHER_ID = t.TEACHER_ID WHERE t.TEACHER_NAME = 'Sir Ali';

--Q20:
SELECT e.* FROM EMPLOYEES e JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID WHERE e.DEPARTMENT_ID = m.DEPARTMENT_ID;
