--Q1:
SELECT SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES;

--Q2:
SELECT AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES;

--Q3:
SELECT COUNT(*) AS TOTAL_EMPLOYEES, MANAGER_ID FROM EMPLOYEES GROUP BY MANAGER_ID;

--Q4:
SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);

--Q5:
SELECT TO_CHAR(SYSDATE, 'DD-MM-YYYY') FROM DUAL;

--Q6:
SELECT TO_CHAR(SYSDATE, 'DAYMONTHYYYY') FROM DUAL;

--Q7:
SELECT * FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'DAY') LIKE 'WED%';

--Q8:
SELECT MONTHS_BETWEEN('01-JAN-2025', '01-OCT-2024') FROM DUAL;

--Q9:
SELECT EMPLOYEE_ID, FIRST_NAME, FLOOR(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS MONTHS_WORKED FROM EMPLOYEES;

--Q10:
SELECT SUBSTR(LAST_NAME, 1, 5) FROM EMPLOYEES;
