--Q11:
SELECT LPAD(FIRST_NAME, 15, '*') FROM EMPLOYEES;

--Q12:
SELECT LTRIM(' Oracle') FROM DUAL;

--Q13:
SELECT INITCAP(FIRST_NAME) FROM EMPLOYEES;

--Q14:
SELECT NEXT_DAY('20-AUG-2022', 'MONDAY') FROM DUAL;

--Q15:
SELECT TO_CHAR(TO_DATE('25-DEC-2009'), 'MM-YYYY') FROM DUAL;

--Q16:
SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY ASC;

--Q17:
SELECT EMPLOYEE_ID, FIRST_NAME, ROUND(SALARY, -2) AS SALARY FROM EMPLOYEES;

--Q18:
SELECT * FROM (SELECT DEPARTMENT_ID, COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY TOTAL_EMPLOYEES DESC) WHERE ROWNUM <= 1;

--Q19:
SELECT * FROM (SELECT DEPARTMENT_ID, SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY TOTAL_SALARY DESC) WHERE ROWNUM <= 3;

--Q20:
SELECT * FROM (SELECT DEPARTMENT_ID, COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY TOTAL_EMPLOYEES DESC) WHERE ROWNUM <= 1;
