SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES;
SELECT COUNT(*) AS TOTAL_EMPLOYEES, MANAGER_ID FROM EMPLOYEES GROUP BY(MANAGER_ID);
SELECT UNIQUE MANAGER_ID FROM EMPLOYEES;
SELECT SUM(SALARY) AS TOTAL_SALARY, MANAGER_ID FROM EMPLOYEES GROUP BY(MANAGER_ID);
SELECT EMPLOYEE_ID, MANAGER_ID, SALARY FROM EMPLOYEES WHERE SALARY = (SELECT SALARY FROM EMPLOYEES);
SELECT FIRST_NAME || ' ' || SALARY AS ABC FROM EMPLOYEES;
SELECT EMPLOYEE_ID FROM EMPLOYEES ORDER BY(SALARY) ASC;
SELECT COUNT(*) FROM EMPLOYEES WHERE FIRST_NAME LIKE 'A%';
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%A%';
SELECT UPPER(FIRST_NAME) FROM EMPLOYEES;
SELECT INITCAP(FIRST_NAME) FROM EMPLOYEES;
SELECT FIRST_NAME, LENGTH(FIRST_NAME) FROM EMPLOYEES;

SELECT * FROM DUAL;
SELECT TRIM('GFBS SHGF') AS A FROM DUAL;
SELECT RPAD('CH', LENGTH('ch') + 5, '*') FROM DUAL;
SELECT NEXT_DAY('28-AUG-25', 'MONDAY') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY') FROM DUAL;

SELECT * FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE, 'DAY') LIKE 'SATURDAY%';
SELECT TO_CHAR(HIRE_DATE, 'DAY') FROM EMPLOYEES;
