--Q1:
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID != 100;

--Q2:
SELECT * FROM EMPLOYEES WHERE SALARY IN(10000, 12000, 15000);

--Q3:
SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY <= 25000;

--Q4:
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID != 60;

--Q5:
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID BETWEEN 60 AND 80;

--Q6:
SELECT * FROM DEPARTMENTS;

--Q7:
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Steven';

--Q8:
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 15000 AND 25000 AND DEPARTMENT_ID = 80;

--Q9:
SELECT * FROM EMPLOYEES WHERE SALARY < ANY(SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 100);

--Q10:
SELECT * FROM EMPLOYEES e0 WHERE e0.EMPLOYEE_ID = ALL(SELECT EMPLOYEE_ID FROM EMPLOYEES e1 WHERE e0.DEPARTMENT_ID = e1.DEPARTMENT_ID); -- METHOD 1
SELECT * FROM EMPLOYEES e0 WHERE NOT EXISTS(SELECT DEPARTMENT_ID FROM EMPLOYEES e1 WHERE e0.EMPLOYEE_ID != e1.EMPLOYEE_ID AND e0.DEPARTMENT_ID = e1.DEPARTMENT_ID);  -- METHOD 2
