--Q11:
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '01-JAN-05' AND '31-DEC-06';

--Q12:
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NULL;

--Q13:
SELECT * FROM EMPLOYEES WHERE SALARY < ALL(SELECT SALARY FROM EMPLOYEES WHERE SALARY > 8000);

--Q14:
SELECT * FROM EMPLOYEES WHERE SALARY > ANY(SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 90);

--Q15:
SELECT * FROM DEPARTMENTS d WHERE EXISTS(SELECT * FROM EMPLOYEES e WHERE d.DEPARTMENT_ID = e.DEPARTMENT_ID); -- METHOD 1
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID = ANY(SELECT DEPARTMENT_ID FROM EMPLOYEES); -- METHOD 2

--Q16:
SELECT * FROM DEPARTMENTS d WHERE NOT EXISTS(SELECT * FROM EMPLOYEES e WHERE d.DEPARTMENT_ID = e.DEPARTMENT_ID); -- METHOD 1
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID != ALL(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL); -- METHOD 2

--Q17:
SELECT * FROM EMPLOYEES WHERE SALARY NOT BETWEEN 5000 AND 15000;

--Q18:
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN(10, 20, 30) AND DEPARTMENT_ID != 40;

--Q19:
SELECT * FROM EMPLOYEES WHERE SALARY < ALL(SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 50);

--Q20:
SELECT * FROM EMPLOYEES WHERE SALARY > ALL(SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 90);
