--Q1:
CREATE TABLE EMPLOYEES (
    EMP_ID INT,
    EMP_NAME VARCHAR(20),
    SALARY INT,
    CONSTRAINT check_salary CHECK(SALARY > 20000),
    DEPT_ID INT
);

--Q2:
ALTER TABLE EMPLOYEES RENAME COLUMN EMP_NAME TO FULL_NAME;

--Q3:
ALTER TABLE EMPLOYEES DROP CONSTRAINT check_salary;
INSERT INTO EMPLOYEES COLUMNS(SALARY) VALUES(5000);

--Q4:
CREATE TABLE DEPARTMENTS (
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(20) UNIQUE
);

INSERT INTO DEPARTMENTS VALUES(1, 'CS');
INSERT INTO DEPARTMENTS VALUES(2, 'SE');
INSERT INTO DEPARTMENTS VALUES(3, 'AI');

--Q5:
ALTER TABLE EMPLOYEES ADD CONSTRAINT foreign_key FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID);

--Q6:
ALTER TABLE EMPLOYEES ADD BONUS NUMBER(6, 2) DEFAULT 1000;

--Q7:
ALTER TABLE EMPLOYEES ADD (
    CITY VARCHAR(20) DEFAULT 'Karachi',
    AGE INT,
    CONSTRAINT check_age CHECK(AGE > 18)
);

--Q8:
INSERT INTO EMPLOYEES(EMP_ID, FULL_NAME, SALARY, DEPT_ID, AGE) VALUES(1, 'A', 15000, 1, 19);
DELETE FROM EMPLOYEES WHERE EMP_ID IN (1, 3);

--Q9:
ALTER TABLE EMPLOYEES MODIFY (
    FULL_NAME VARCHAR(20),
    CITY VARCHAR(20) DEFAULT 'Karachi'
);

--Q10:
ALTER TABLE EMPLOYEES ADD EMAIL VARCHAR(20);
ALTER TABLE EMPLOYEES ADD CONSTRAINT unique_email UNIQUE(EMAIL);
