--Q11:
ALTER TABLE EMPLOYEES ADD CONSTRAINT unique_bonus UNIQUE(BONUS);
INSERT INTO EMPLOYEES COLUMNS(BONUS) VALUES(500);
INSERT INTO EMPLOYEES COLUMNS(BONUS) VALUES(500); -- Produces Error

--Q12:
ALTER TABLE EMPLOYEES ADD DOB DATE;
ALTER TABLE EMPLOYEES ADD CONSTRAINT check_dob CHECK(MONTHS_BETWEEN('07-SEP-2025', DOB) >= 204);

--Q13:
INSERT INTO EMPLOYEES COLUMNS(DOB) VALUES ('01-JAN-2010');

--Q14:
ALTER TABLE EMPLOYEES DROP CONSTRAINT foreign_key;
INSERT INTO EMPLOYEES COLUMNS(BONUS, DEPT_ID) VALUES(50, 5);
ALTER TABLE EMPLOYEES ADD CONSTRAINT foreign_key FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID); -- Producing error

--Q15:
ALTER TABLE EMPLOYEES DROP COLUMN AGE;
ALTER TABLE EMPLOYEES DROP COLUMN CITY;

--Q16:
SELECT d.DEPT_ID, d.DEPT_NAME, e.EMP_ID, FULL_NAME FROM DEPARTMENTS d LEFT JOIN EMPLOYEES e ON d.DEPT_ID = e.DEPT_ID ORDER BY d.DEPT_ID;

--Q17:
ALTER TABLE EMPLOYEES RENAME COLUMN SALARY TO MONTHLY_SALARY;

--Q18:
SELECT * FROM DEPARTMENTS d WHERE NOT EXISTS (SELECT DEPT_ID FROM EMPLOYEES e WHERE e.DEPT_ID = d.DEPT_ID);

--Q19:
CREATE TABLE STUDENTS(ID INT);
DELETE FROM STUDENTS;

--Q20:
SELECT * FROM (SELECT DEPT_ID, COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES WHERE DEPT_ID IS NOT NULL GROUP BY DEPT_ID ORDER BY TOTAL_EMPLOYEES DESC) WHERE ROWNUM <= 1;
