CREATE TABLE STUDENTS(
    ID INT PRIMARY KEY,
    STD_NAME VARCHAR(30),
    EMAIL VARCHAR(20),
    AGE INT,
    CHECK(AGE >= 18)
);

ALTER TABLE STUDENTS ADD SALARY INT;
ALTER TABLE STUDENTS ADD (CITY VARCHAR(20) DEFAULT 'Karachi', DEPT_ID INT);

ALTER TABLE STUDENTS ADD CONSTRAINT UNIQUE_EMAIL UNIQUE(EMAIL);
ALTER TABLE STUDENTS MODIFY(
    STD_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL
);

ALTER TABLE STUDENTS ADD(
    CONSTRAINT CHECK_AGE CHECK(AGE BETWEEN 18 AND 30),
    CONSTRAINT UNIQUE_EMAIL UNIQUE(EMAIL)
); --Dont Run

CREATE TABLE DEPARTMENTS(
    ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(20) NOT NULL
);

SELECT * FROM DEPARTMENTS;

INSERT INTO DEPARTMENTS(ID, DEPT_NAME) VALUES(4, 'AI');

ALTER TABLE STUDENTS DROP COLUMN DEPT_ID;

ALTER TABLE STUDENTS ADD (DEPT_ID INT, FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENTS(ID));

INSERT INTO STUDENTS(ID, STD_NAME, EMAIL, AGE, SALARY, CITY, DEPT_ID) VALUES(4, 'AR', 'ar@gmail.com', 25, 500, 'Karachi', 3);

SELECT * FROM STUDENTS;

DELETE FROM STUDENTS WHERE ID IN(1, 2, 3, 4);
